language: cpp
dist: xenial
compiler:
  - gcc
  - clang
env:
  - CONFIG=minimal
  - CONFIG=full
install:
  - autotest/travis/install-build-depends.sh
script:
  - autotest/travis/build-and-test.sh
dist: xenial

